name: Build and Push Docker Image

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        env:
          REGISTRY: ${{ secrets.AWS_ACCESS_KEY_ID }}
          REPOSITORY: express-api-ecs
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker login -u $REGISTRY -p ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          echo "AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}"
