name: Build and Push Docker Image

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and push Docker image
        env:
          REGISTRY: ${{ secrets.AWS_ACCESS_KEY_ID }}
          REPOSITORY: 622307425282.dkr.ecr.eu-central-1.amazonaws.com/ecrtesting
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
