name: mysql
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        ports:
          - 3306
        env:
          MYSQL_ROOT_PASSWORD: root123
          MYSQL_DATABASE: test_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
        options: >-
          --health-cmd "mysqladmin ping -h 127.0.0.1 --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
      - name: Wait for MySQL
        run: |
          timeout 60s bash -c "while ! mysqladmin ping -h\"127.0.0.1\" --silent; do sleep 1; done"
          echo "MySQL is up and running"
      - name: Run tests
        env:
          DATABASE_URL: mysql://test_user:test_password@127.0.0.1:3306/test_db
        run: npm test
