name: mysql
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        ports:
          - 5050:3306
        env:
          MYSQL_ROOT_PASSWORD: root123
          MYSQL_DATABASE: test_db
        options: >-
          --health-cmd "mysqladmin ping -h localhost --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: |
          mysql -h localhost -P 5050 -u root -p${MYSQL_ROOT_PASSWORD} test_db -e "SELECT 1"
